controllers/CategoryController.php
<?php
/**
 * CategoryController class file
 *
 * @author Joachim Werner <joachim.werner@diggin-data.de>
 * @package download.controllers
 */

class CategoryController extends Controller
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';

    public $defaultAction='index';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update' /* ,'admin','delete' */),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model=new DownloadCategory;
        $model->status = DownloadCategory::STATUS_DRAFT;

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['DownloadCategory']))
        {
            $model->attributes=$_POST['DownloadCategory'];
            if($model->save()) {
                Yii::app()->user->setFlash('success',Yii::t('DownloadModule.main','<strong>Creating New Item</strong><br />The item with ID #{id} has been created.',array('{id}'=>$model->id)));
                $this->redirect(array('view','id'=>$model->id));
            } else {
                Yii::app()->user->setFlash('error',Yii::t('DownloadModule.main','<strong>Error Creating New Item</strong><br />Couldn\'t create a new item.'));
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    }

    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['DownloadCategory']))
        {
            $model->attributes=$_POST['DownloadCategory'];
            if($model->save()) {
                Yii::app()->user->setFlash('success',Yii::t('DownloadModule.main','<strong>Updating Item</strong><br />The item with ID #{id} has been updated.',array('{id}'=>$model->id)));
                $this->redirect(array('view','id'=>$model->id));
            } else {
                Yii::app()->user->setFlash('error',Yii::t('DownloadModule.main','<strong>Error Updating Item</strong><br />Couldn\'t update item with ID #{id}.',array('{id}'=>$model->id)));
            }
        }

        $this->render('update',array(
            'model'=>$model,
        ));
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete($id)
    {
        if(Yii::app()->request->isPostRequest)
        {
            // we only allow deletion via POST request
            $result = $this->loadModel($id)->delete();

            // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
            if(!isset($_GET['ajax'])) {
                if($result==true) {
                    Yii::app()->user->setFlash('success',Yii::t('DownloadModule.main','<strong>Deleting Item</strong><br />The item with ID #{id} has been deleted.',array('{id}'=>$model->id)));
                    $this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
                } else {
                    Yii::app()->user->setFlash('error',Yii::t('DownloadModule.main','<strong>Error on Deleting Item</strong><br />The item with ID #{id} couldn\'t be deleted.',array('{id}'=>$model->id)));
                }
            }
        }
        else
            throw new CHttpException(400,Yii::t('DownloadModule.main','Invalid request. Please do not repeat this request again.'));
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $model=new DownloadCategory('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['DownloadCategory']))
            $model->attributes=$_GET['DownloadCategory'];
        else
            $model->parentId=0;

        $dataProvider=$model->search(); // new CActiveDataProvider('DownloadCategory');
        $this->render('index',array(
            'dataProvider'=>$dataProvider,
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model=new DownloadCategory('search');
        $model->unsetAttributes();  // clear any default values
        if(isset($_GET['DownloadCategory']))
            $model->attributes=$_GET['DownloadCategory'];

        $this->render('admin',array(
            'model'=>$model,
        ));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer the ID of the model to be loaded
     */
    public function loadModel($id)
    {
        $model=DownloadCategory::model()->findByPk($id);
        if($model===null)
            throw new CHttpException(404,Yii::t('DownloadModule.main','The requested page does not exist.'));
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param CModel the model to be validated
     */
    protected function performAjaxValidation($model)
    {
        if(isset($_POST['ajax']) && $_POST['ajax']==='download-category-form')
        {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }
}

controllers/FileController.php
<?php
/**
 * FileController class file
 *
 * @author Joachim Werner <joachim.werner@diggin-data.de>
 * @package download.controllers
 */

class FileController extends Controller
{
    // {{{ *** Members ***
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;
    // }}} End Members
    // {{{ *** Methods ***
    // {{{ filters
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    } // }}} 
    // {{{ accessRules
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','preview','download'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update' /* ,'admin','delete' */),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete','resetDownloadCounter'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    } // }}} 
    // {{{ actionView
    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    } // }}} 
    // {{{ actionPreview
    public function actionPreview($image=null, $x=0, $y=0, $src_x=0, $src_y=0, $src_w=0, $src_h=0, $resize=0, $aspectratio=1)
    {
        $image = str_replace('|',DIRECTORY_SEPARATOR, $image);
        $argKeys = array('image', 'x', 'y', 'src_x', 'src_y', 'src_w', 'src_h', 'resize', 'aspectratio');
        error_reporting(E_ALL ^ E_NOTICE);
        $types = array (1 => "gif", "jpeg", "png", "swf", "psd", "wbmp");

        // Set file name
        if(!isset($image)) {
            die('Es wurde kein Bild angegeben!');
        } else {
             if(!file_exists($image))
                 die('Die angegebene Datei konnte nicht auf dem Server gefunden werden!');
        }

        // Do we have a folder?
        if(is_dir($image)) {
            header('Content-Type: image/png');
            readfile('images/filetypeicons/folder.png');
            die;
        }

        // Do we have a non-image file?
        $mimeType = mime_content_type($image);
        if(strpos($mimeType,'image/')===false) {
            // No image
            if(preg_match("/\.([^\.]+)$/",$image,$matches)){
                $extension = $matches[1];
                $iconPath = dirname(__FILE__).'/../../../../'.str_replace(Yii::app()->baseUrl.'/', '',$this->module->assetsUrl).'/filetypeicons';
                $extensionIcon = $iconPath.'/'.$this->getFileIconByExtension($extension);
                if(!file_exists($extensionIcon))
                    $extensionIcon=$iconPath.'/fileicon_bg.png';
                header('Content-Type: image/png');
                readfile($extensionIcon);
                die;
            }
        }

        if(
        (is_null($x) && is_null($y))  
        ) {
           die('Fehlende(r) oder ungültige(r) Größenparameter!');
        }

        $cacheSubDir = '.thumbs';
        $fileDir = dirname($image);
        $cacheDir = $fileDir.'/'.$cacheSubDir;
        // Create thumbs dir?
        if(!is_dir ($cacheDir))
            @mkdir($cacheDir, 0777);

        $imagedata = getimagesize($image);

        if(!isset($imagedata[2]) || $imagedata[2] == 4 || $imagedata[2] == 5)
            die('Bei der angegebenen Datei handelt es sich nicht um ein Bild!');

        if($x==0)
            $x = floor ($y * $imagedata[0] / $imagedata[1]);

        if($y==0)
            $y = floor ($x * $imagedata[1] / $imagedata[0]);

        if ($aspectratio) {
             if ($imagedata[0] > $imagedata[1]) { // Breite > Höhe
                  $y = floor ($x * $imagedata[1] / $imagedata[0]); // Neue Breite * Verh. H/B
             } else if ($imagedata[1] > $imagedata[0]) {
                  $x = floor ($y * $imagedata[0] / $imagedata[1]); // Neue Höhe * Verh. B/H
             }
        }
        // src_w
        if($src_w==0)
            $src_w = $imagedata[0];
        // src_h
        if($src_h==0)
            $src_h = $imagedata[1];

        $dst_x = 0;
        $dst_y = 0;

        $myArgs = func_get_args();
        $tmp = array();
        for($i=1; $i<count($myArgs); $i++) {
            $tmp[] = $argKeys[$i].'='.$myArgs[$i];
        }
        $thumbfile = md5(join('&',$tmp)).'_'.basename($image);

        if (file_exists ($cacheDir.'/'.$thumbfile)) {
             $thumbdata = getimagesize ($cacheDir.'/'.$thumbfile);
             $thumbdata[0] == $x && $thumbdata[1] == $y
                  ? $iscached = true
                  : $iscached = false;
        } else {
             $iscached = false;
        }

        if (!$iscached) {
             ($imagedata[0] > $x || $imagedata[1] > $y) ||
             (($imagedata[0] < $x || $imagedata[1] < $y) && $resize)
                  ? $makethumb = true
                  : $makethumb = false;
        } else {
             $makethumb = false;
        }

        Header( "Content-Type: image/".$types[$imagedata[2]] );

        if ($makethumb) {
             $image = call_user_func("imagecreatefrom".$types[$imagedata[2]], $image);
             $thumb = imagecreatetruecolor ($x, $y);
             // imagecopyresized ( resource $dst_image , resource $src_image , int $dst_x , int $dst_y , int $src_x , int $src_y , int $dst_w , int $dst_h , int $src_w , int $src_h ) 
             imagecopyresized (
                 $thumb,    // destination image
                 $image,    // source image 
                 $dst_x,    // dest. x
                 $dst_y,    // dest. y
                 $src_x,    // source x
                 $src_y,    // source y
                 $x,        // dest. width
                 $y,        // dest. height
                 $src_w, 
                 $src_h
             );
             call_user_func("image".$types[$imagedata[2]], $thumb, $cacheDir.'/'.$thumbfile);
             imagedestroy ($image);
             imagedestroy ($thumb);
             $image = $cacheDir.'/'.$thumbfile;
        } else {
             $iscached
                  ? $image = $cacheDir.'/'.$thumbfile
                  : $image = $image;
        }
        Header( "Content-Length: ".filesize($image) );
        $image = fopen ($image, "rb");
        fpassthru ($image);
        fclose ($image);
        die;
    } // }}}
    // {{{ actionDownload
    public function actionDownload($id)
    {
        $model = $this->loadModel($id);
        header("Content-Type: ".$model->mimeType);
        header("Content-Disposition: attachment; filename=\"{$model->fileName}\"");
        readfile($model->pathToFile.DIRECTORY_SEPARATOR.md5($model->fileName));
        $model->incrementDownloadCounter();
        die;
    } // }}} 
    // {{{ actionResetDownloadCounter
    public function actionResetDownloadCounter($id)
    {
        $model = $this->loadModel($id);
        $model->resetDownloadCounter();
        $this->redirect(array('view', 'id'=>$id));
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model          = new DownloadFile;
        $model->version = 1;

        if(isset($_GET['DownloadFile']))
            $model->attributes=$_GET['DownloadFile'];

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['DownloadFile']))
        {
            $model->attributes  = $_POST['DownloadFile'];
            $model->mimeType    = $_FILES['DownloadFile']['type']['pathToFile'];
            $uploadedFile       = CUploadedFile::getInstance($model,'pathToFile');
            $model->pathToFile  = $this->module->baseDir;
            $model->fileName    = $uploadedFile->name;

            if($model->save()) {
                if(!empty($uploadedFile))  // check if uploaded file is set or not
                {
                    $uploadedFile->saveAs($model->pathToFile.DIRECTORY_SEPARATOR.md5($model->fileName));  // file will uplode to rootDirectory/files/
                }
                Yii::app()->user->setFlash('success',Yii::t('DownloadModule.main','<strong>Creating New Item</strong><br />The item with ID #{id} has been created.',array('{id}'=>$model->id)));
                $this->redirect(array('view','id'=>$model->id));
            } else {
                Yii::app()->user->setFlash('error',Yii::t('DownloadModule.main','<strong>Error Creating New Item</strong><br />Couldn\'t create a new item.'));
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    } // }}} 
    // {{{ actionUpdate
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed

views/file/_view.php
<div class="navbar-inner" style="padding:15px">

    <div class="row-fluid">

    <div class="span3">
        <p>
        <?php echo CHtml::link(
            CHtml::image(
                $this->createUrl('preview', array('image'=>str_replace(DIRECTORY_SEPARATOR,'|',$data->pathToFile.DIRECTORY_SEPARATOR.md5($data->fileName)), 'x'=>100)),
                $data->fileName, 
                array('width'=>100, 'style'=>'border:1px solid #aaa;padding:3px;')
            ),
            $this->createUrl('download',array('id'=>$data->id)),
            array('title'=>Yii::t('DownloadModule.main','Download {fileName}', array('{fileName}'=>$data->fileName)))
        ); ?>
        </p>

        <p>
        <a class="btn btn-mini btn-primary" href="<?php echo $this->createUrl('download',array('id'=>$data->id)); ?>"><i class="icon-download-alt icon-white"></i>&nbsp;<?php echo Yii::t('DownloadModule.main','Download File'); ?></a>
        </p>

    </div>

    <div class="span3">

        <b><?php echo CHtml::encode($data->getAttributeLabel('categoryId')); ?>:</b><br />
        <?php echo CHtml::link($data->category->recordName,array('file/index', 'DownloadFile[categoryId]'=>$data->categoryId)); ?>
        <br />

        <b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b><br />
        <?php echo CHtml::encode($data->title); ?>
        <br />

        <b><?php echo CHtml::encode($data->getAttributeLabel('fileName')); ?>:</b><br />
        <?php echo CHtml::encode($data->fileName); ?>

    </div>
    
    <div class="span3">

        <b><?php echo CHtml::encode($data->getAttributeLabel('subTitle')); ?>:</b><br />
        <?php echo CHtml::encode($data->subTitle); ?>
        <br />

        <b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b><br />
        <?php echo CHtml::encode($data->description); ?>
        <br />

        <b><?php echo CHtml::encode($data->getAttributeLabel('version')); ?>:</b><br />
        <?php echo CHtml::encode($data->version); ?>
        <br />

    </div>

    </div><!-- end div.row-fluid -->

</div>

views/file/admin.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
    Yii::t('DownloadModule.main','Download Files')=>array('index'),
    Yii::t('DownloadModule.main','Manage'),
);

$this->menu=array(
    array('label'=>Yii::t('DownloadModule.main','Create New Download File'),'url'=>array('create'), 'icon'=>'star'),
    array('label'=>Yii::t('DownloadModule.main','List Download Files'),'url'=>array('index'), 'icon'=>'th-large'),
    array('label'=>Yii::t('DownloadModule.main','Related Links'),'itemOptions'=>array('class'=>'nav-header')),
    array('label'=>Yii::t('DownloadModule.main','Download Categories'),'url'=>array('category/admin'), 'icon'=>'th-list'),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
    $('.search-form').toggle();
    $('#DownloadFile_title').focus().select();
    return false;
});
$('.search-form form').submit(function(){
    $.fn.yiiGridView.update('download-file-grid', {
        data: $(this).serialize()
    });
    return false;
});
");
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','Manage Download Files')); ?></h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link(Yii::t('DownloadModule.main','Advanced Search'),'#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
    'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
    'id'=>'download-file-grid',
    'type'=>'striped condensed',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'htmlOptions'=>array('style'=>'cursor: pointer;'),
    'selectionChanged'=>"function(id){window.location='" . Yii::app()->urlManager->createUrl('/download/file/view', array('id'=>'')) . "/' + $.fn.yiiGridView.getSelection(id);}",
    'columns'=>array(
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{view}{update}',
        ),
        array(
            'name'=>'categoryId',
            'value'=>'CHtml::link($data->category->recordName,array("category/view", "id"=>$data->categoryId))',
            'type'=>'raw',
            'filter'=>CHtml::listData(DownloadCategory::model()->findAll(array('order'=>'title')), 'id', 'title'),
        ),      
        'title',
        'subTitle',
        'fileName',
        array(
            'name'=>'mimeType',
        ),
        array(
            'name'=>'version',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'name'=>'downloadCounter',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{delete}',
        ),
    ),
)); ?>

views/file/create.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
	Yii::t('DownloadModule.main','Download Files')=>array('index'),
	Yii::t('DownloadModule.main','Create'),
);

$this->menu=array(
	array('label'=>Yii::t('DownloadModule.main','List Download Files'),'url'=>array('index'), 'icon'=>'th-large'),
	array('label'=>Yii::t('DownloadModule.main','Manage Download Files'),'url'=>array('admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','Create a New Download File')); ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

views/file/index.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download/category/index'),
	Yii::t('DownloadModule.main','Download Files'),
);

$this->menu=array(
	array('label'=>Yii::t('DownloadModule.main','Create New Download File'),'url'=>array('create'), 'icon'=>'star'),
	array('label'=>Yii::t('DownloadModule.main','Manage'),'url'=>array('admin'), 'icon'=>'th-list'),
    array('label'=>Yii::t('DownloadModule.main','Related Links'),'itemOptions'=>array('class'=>'nav-header')),
    array('label'=>Yii::t('DownloadModule.main','Download Categories'),'url'=>array('category/admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','Download Files')); ?></h1>

<?php if(isset($_GET['DownloadFile']['categoryId'])) : $category = DownloadCategory::model()->findByPk($_GET['DownloadFile']['categoryId']); ?>
    <?php if(!is_null($category)) : ?>
    <?php $this->renderPartial('/category/_view', array('data'=>$category)); ?>
    <?php endif; ?>
<?php endif; ?>


<?php $this->widget('bootstrap.widgets.TbListView',array(
	'dataProvider'=>$dataProvider,
    'itemView'=>'_view',
    'template'=>'{sorter}{pager}{summary}{items}{sorter}{pager}',
    'sortableAttributes'=>array(
        'categoryId',
        'title',
        'subTitle',
        // TODO: Uncomment the following attributes to show them as sort links in list view
    // 'pathToFile',
        // 'description',
        // 'version',
    ),
)); ?>

views/file/view.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
	Yii::t('DownloadModule.main','Download Files')=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>Yii::t('DownloadModule.main','Update Download File'),'url'=>array('update','id'=>$model->id), 'icon'=>'pencil'),
	array('label'=>Yii::t('DownloadModule.main','User View'),'url'=>array('file/index','DownloadFile[categoryId]'=>$model->categoryId), 'icon'=>'zoom-in'),
	array('label'=>Yii::t('DownloadModule.main','Delete Download File'),'url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?'), 'icon'=>'remove'),
	array('label'=>Yii::t('DownloadModule.main','Create New Download File'),'url'=>array('create'), 'icon'=>'star'),
	array('label'=>Yii::t('DownloadModule.main','List Download Files'),'url'=>array('index'), 'icon'=>'th-large'),
	array('label'=>Yii::t('DownloadModule.main','Manage Download Files'),'url'=>array('admin'), 'icon'=>'th-list'),
    array('label'=>Yii::t('DownloadModule.main','Related Links'),'itemOptions'=>array('class'=>'nav-header')),
    array('label'=>Yii::t('DownloadModule.main','Download Categories'),'url'=>array('category/admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','View Download File {recordName}',array('{recordName}'=>$model->recordName))); ?></h1>

<?php
$stats = $model->stats;
$this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		'id',
        array(
            'name'=>'categoryId',
            'value'=>CHtml::link($model->category->recordName,array('category/view', 'id'=>$model->categoryId)),
            'type'=>'raw',
        ),
		'title',
		'subTitle',
		'description',
        array(
            'name'=>'pathToFile',
            'value'=>$model->getRelativePath(),
        ),
        'fileName',
        'version',
        array(
            'label'=>'Preview',
            'type'=>'raw',
            'value'=>CHtml::image($this->createUrl('preview', array('image'=>str_replace(DIRECTORY_SEPARATOR,'|',$model->pathToFile.DIRECTORY_SEPARATOR.md5($model->fileName)), 'x'=>100), array('width'=>100))),
        ),
        array(
            'label'=>'Download',
            'type'=>'raw',
            'value'=>'<a class="btn btn-primary" '
                .'href="'.$this->createUrl('download',array('id'=>$model->id)).'">'
                .'<i class="icon-download-alt icon-white"></i> '
                .Yii::t('DownloadModule.main','Download {fileName}', array('{fileName}'=>$model->fileName))
                .'</a>',
        ),
        array(
            'label'=>'Size',
            'value'=>$model->formatBytes($stats['size']),
        ),
        array(
            'label'=>'Last Accessed',
            'value'=>Yii::app()->dateFormatter->formatDateTime($stats['atime'],'medium','short'),
        ),
        array(
            'label'=>'Last Inode Change Time',
            'value'=>Yii::app()->dateFormatter->formatDateTime($stats['ctime'],'medium','short'),
        ),
        array(
            'label'=>'Last Modification Time',
            'value'=>Yii::app()->dateFormatter->formatDateTime($stats['ctime'],'medium','short'),
        ),
        array(
            'name'=>'downloadCounter',
            'type'=>'raw',
            'value'=>$model->downloadCounter>0 ? CHtml::link(Yii::t('DownloadModule.main','{downloadCounter} (Reset)', array('{downloadCounter}'=>$model->downloadCounter)), array('resetDownloadCounter', 'id'=>$model->id)) : '0',
        ),
        array(
            'label'=>'Last Download Timestamp',
            'value'=>Yii::app()->dateFormatter->formatDateTime($model->lastDownloadedTs,'medium','short'),
        ),
	),
));
?>

<?php $this->widget('ext.diggindata.ddtimestamp.widgets.DDTimestamp', array(
    'model'=>$model, 
    'title'=>Yii::t('site','Change Log'),
    'detailViewWidget'=>'bootstrap.widgets.TbDetailView'
)); ?>