models/DownloadCategory.php
<?php

/**
 * This is the model class for table "{{dl_category}}".
 *
 * The followings are the available columns in table '{{dl_category}}':
 * @property integer $id
 * @property integer $parentId
 * @property string $title
 * @property integer $description
 * @property string $authItems
 * @property integer $status
 */
class DownloadCategory extends Model
{
    // {{{ *** Members ***
    /**
     * @var string
     */
    public $nameFields = "title";
    /**
     * @var string
     */
    public $nameFormat = "{1}";

    public $filesCount;
    
    const STATUS_DRAFT=1;
    const STATUS_PUBLISHED=2;
    const STATUS_ARCHIVED=3;
    // }}} End Members
    // {{{ *** Methods ***
    // {{{ model
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return DownloadCategory the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	} // }}} 
    // {{{ tableName
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return '{{dl_category}}';
	} // }}} 
    // {{{ behaviors
    public function behaviors()
    {
        return array(
            'datetimeI18NBehavior' => array(
                // 'ext' is in Yii 1.0.8 version. For early versions, use 'application.extensions' instead.
                'class' => 'ext.DateTimeI18NBehavior'
            ),
            'DDTimestampBehavior' => array(
                'class'                 => 'ext.diggindata.ddtimestamp.behaviors.DDTimestampBehavior',
                'timestampTableName'    => '{{artimestamp}}',
                'userClassName'         => 'User',
                'userNameAttribute'     => 'recordName',
                'setUpdateOnCreate'     => true,
            )
        ); 
    } // }}} 
    // {{{ rules
	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('parentId, title, status', 'required'),
			array('parentId, status', 'numerical', 'integerOnly'=>true),
            array('title', 'length', 'max'=>255),
            array('description, authItems', 'safe'),
			// The following rule is used by search().
			// Please remove those attributes that should not be searched.
			array('id, parentId, title, description, authItems, status, filesCount', 'safe', 'on'=>'search'),
		);
	} // }}} 
    // {{{ relations
	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
        return array(
            'parent'=>array(self::BELONGS_TO,'DownloadCategory', 'parentId'),
            'children'=>array(self::HAS_MANY,'DownloadCategory', 'parentId', 'order'=>'title'),
            'files'=>array(self::HAS_MANY,'DownloadFile','categoryId'),
		);
	} // }}} 
    // {{{ attributeLabels
	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => Yii::t('DownloadModule.main','ID'),
			'parentId' => Yii::t('DownloadModule.main','Parent Category'),
			'title' => Yii::t('DownloadModule.main','Title'),
			'description' => Yii::t('DownloadModule.main','Description'),
			'authItems' => Yii::t('DownloadModule.main','Auth Items'),
            'status' => Yii::t('DownloadModule.main','Status'),
            'filesCount' => Yii::t('DownloadModule.main','Files'),
		);
	} // }}} 
    // {{{ search
	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		// Warning: Please modify the following code to remove attributes that
		// should not be searched.

        $criteria=new CDbCriteria;
        $criteria->with = array('files');

        // sub query to retrieve the count of posts
        $files_table = DownloadFile::model()->tableName();
        $files_count_sql = "(select count(*) from $files_table where $files_table.categoryId = t.id)";

        // select
        $criteria->select = array(
            '*',
            $files_count_sql . " AS filesCount",
        );
        
		$criteria->compare('id',$this->id);
		$criteria->compare('parentId',$this->parentId);
		$criteria->compare('title',$this->title,true);
		$criteria->compare('description',$this->description);
		$criteria->compare('authItems',$this->authItems,true);
		$criteria->compare('status',$this->status);

		return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
            'sort' => array(
                'defaultOrder' => 't.title',
                'attributes' => array(
                    // order by
                    'filesCount' => array(
                        'asc' => 'filesCount ASC',
                        'desc' => 'filesCount DESC',
                    ),
                    '*',
                ),
            ),
		));
	} // }}} 
    // {{{ getStatusOptions
    /**
     * Returns an array of status descriptions, indexed by status codes
     *
     * @return mixed
     */
    public function getStatusOptions()
    {
        return array(
            self::STATUS_DRAFT      => Yii::t('BlogModule.main','Draft'),
            self::STATUS_PUBLISHED  => Yii::t('BlogModule.main','Published'),
            self::STATUS_ARCHIVED   => Yii::t('BlogModule.main','Archived'),
        );
    } // }}} 
    // {{{ getParentOptions
    public function getParentOptions()
    {
        $result = array(
            0=>Yii::t('DownloadModule.main','(Root)')
        );
        foreach($this->findAll(array('order'=>'title')) as $model)
            $result[$model->id] = $model->title;

        return $result;
    } // }}} 
    // {{{ getParentLink
    public function getParentLink($target='category')
    {
        if($this->parentId==0)
            return Yii::t('DownloadModule.main','(Root)');
        if(!is_null($this->parent)) {
            if($target=='category')
                return CHtml::link($this->parent->recordName, array('category/view', 'id'=>$this->parentId));
            elseif($target=='files')
                return '<i class="icon-arrow-up"></i> '.CHtml::link($this->parent->recordName, array('file/index', 'DownloadFile[categoryId]'=>$this->parentId));
        }
        else
            return '?';

    } // }}} 
    // {{{ getChildrenLinks
    public function getChildrenLinks($target='category')
    {
        $result = array();
        foreach($this->children as $child) {
            if($target=='category')
                $result[] = CHtml::link($child->recordName, array('category/view', 'id'=>$child->id));
            elseif( $target=='files' )
                $result[] = '<i class="icon-arrow-right"></i> '.CHtml::link($child->recordName, array('file/index', 'DownloadFile[categoryId]'=>$child->id));
        }
        if(count($result)==0)
            $result = array(Yii::t('DownloadModule.main','(none)'));
        return $result;
    } // }}} 
    // }}} End Methods
}

controllers/FileController.php
<?php
/**
 * FileController class file
 *
 * @author Joachim Werner <joachim.werner@diggin-data.de>
 * @package download.controllers
 */

class FileController extends Controller
{
    // {{{ *** Members ***
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column2';

    /**
     * @var CActiveRecord the currently loaded data model instance.
     */
    private $_model;
    // }}} End Members
    // {{{ *** Methods ***
    // {{{ filters
    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
        );
    } // }}} 
    // {{{ accessRules
    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','preview','download'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update' /* ,'admin','delete' */),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete','resetDownloadCounter'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    } // }}} 
    // {{{ actionView
    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    } // }}} 
    // {{{ actionPreview
    public function actionPreview($image=null, $x=0, $y=0, $src_x=0, $src_y=0, $src_w=0, $src_h=0, $resize=0, $aspectratio=1)
    {
        $image = str_replace('|',DIRECTORY_SEPARATOR, $image);
        $argKeys = array('image', 'x', 'y', 'src_x', 'src_y', 'src_w', 'src_h', 'resize', 'aspectratio');
        error_reporting(E_ALL ^ E_NOTICE);
        $types = array (1 => "gif", "jpeg", "png", "swf", "psd", "wbmp");

        // Set file name
        if(!isset($image)) {
            die('Es wurde kein Bild angegeben!');
        } else {
             if(!file_exists($image))
                 die('Die angegebene Datei konnte nicht auf dem Server gefunden werden!');
        }

        // Do we have a folder?
        if(is_dir($image)) {
            header('Content-Type: image/png');
            readfile('images/filetypeicons/folder.png');
            die;
        }

        // Do we have a non-image file?
        $mimeType = mime_content_type($image);
        if(strpos($mimeType,'image/')===false) {
            // No image
            if(preg_match("/\.([^\.]+)$/",$image,$matches)){
                $extension = $matches[1];
                $iconPath = dirname(__FILE__).'/../../../../'.str_replace(Yii::app()->baseUrl.'/', '',$this->module->assetsUrl).'/filetypeicons';
                $extensionIcon = $iconPath.'/'.$this->getFileIconByExtension($extension);
                if(!file_exists($extensionIcon))
                    $extensionIcon=$iconPath.'/fileicon_bg.png';
                header('Content-Type: image/png');
                readfile($extensionIcon);
                die;
            }
        }

        if(
        (is_null($x) && is_null($y))  
        ) {
           die('Fehlende(r) oder ungültige(r) Größenparameter!');
        }

        $cacheSubDir = '.thumbs';
        $fileDir = dirname($image);
        $cacheDir = $fileDir.'/'.$cacheSubDir;
        // Create thumbs dir?
        if(!is_dir ($cacheDir))
            @mkdir($cacheDir, 0777);

        $imagedata = getimagesize($image);

        if(!isset($imagedata[2]) || $imagedata[2] == 4 || $imagedata[2] == 5)
            die('Bei der angegebenen Datei handelt es sich nicht um ein Bild!');

        if($x==0)
            $x = floor ($y * $imagedata[0] / $imagedata[1]);

        if($y==0)
            $y = floor ($x * $imagedata[1] / $imagedata[0]);

        if ($aspectratio) {
             if ($imagedata[0] > $imagedata[1]) { // Breite > Höhe
                  $y = floor ($x * $imagedata[1] / $imagedata[0]); // Neue Breite * Verh. H/B
             } else if ($imagedata[1] > $imagedata[0]) {
                  $x = floor ($y * $imagedata[0] / $imagedata[1]); // Neue Höhe * Verh. B/H
             }
        }
        // src_w
        if($src_w==0)
            $src_w = $imagedata[0];
        // src_h
        if($src_h==0)
            $src_h = $imagedata[1];

        $dst_x = 0;
        $dst_y = 0;

        $myArgs = func_get_args();
        $tmp = array();
        for($i=1; $i<count($myArgs); $i++) {
            $tmp[] = $argKeys[$i].'='.$myArgs[$i];
        }
        $thumbfile = md5(join('&',$tmp)).'_'.basename($image);

        if (file_exists ($cacheDir.'/'.$thumbfile)) {
             $thumbdata = getimagesize ($cacheDir.'/'.$thumbfile);
             $thumbdata[0] == $x && $thumbdata[1] == $y
                  ? $iscached = true
                  : $iscached = false;
        } else {
             $iscached = false;
        }

        if (!$iscached) {
             ($imagedata[0] > $x || $imagedata[1] > $y) ||
             (($imagedata[0] < $x || $imagedata[1] < $y) && $resize)
                  ? $makethumb = true
                  : $makethumb = false;
        } else {
             $makethumb = false;
        }

        Header( "Content-Type: image/".$types[$imagedata[2]] );

        if ($makethumb) {
             $image = call_user_func("imagecreatefrom".$types[$imagedata[2]], $image);
             $thumb = imagecreatetruecolor ($x, $y);
             // imagecopyresized ( resource $dst_image , resource $src_image , int $dst_x , int $dst_y , int $src_x , int $src_y , int $dst_w , int $dst_h , int $src_w , int $src_h ) 
             imagecopyresized (
                 $thumb,    // destination image
                 $image,    // source image 
                 $dst_x,    // dest. x
                 $dst_y,    // dest. y
                 $src_x,    // source x
                 $src_y,    // source y
                 $x,        // dest. width
                 $y,        // dest. height
                 $src_w, 
                 $src_h
             );
             call_user_func("image".$types[$imagedata[2]], $thumb, $cacheDir.'/'.$thumbfile);
             imagedestroy ($image);
             imagedestroy ($thumb);
             $image = $cacheDir.'/'.$thumbfile;
        } else {
             $iscached
                  ? $image = $cacheDir.'/'.$thumbfile
                  : $image = $image;
        }
        Header( "Content-Length: ".filesize($image) );
        $image = fopen ($image, "rb");
        fpassthru ($image);
        fclose ($image);
        die;
    } // }}}
    // {{{ actionDownload
    public function actionDownload($id)
    {
        $model = $this->loadModel($id);
        header("Content-Type: ".$model->mimeType);
        header("Content-Disposition: attachment; filename=\"{$model->fileName}\"");
        readfile($model->pathToFile.DIRECTORY_SEPARATOR.md5($model->fileName));
        $model->incrementDownloadCounter();
        die;
    } // }}} 
    // {{{ actionResetDownloadCounter
    public function actionResetDownloadCounter($id)
    {
        $model = $this->loadModel($id);
        $model->resetDownloadCounter();
        $this->redirect(array('view', 'id'=>$id));
    } // }}} 
    // {{{ actionCreate
    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model          = new DownloadFile;
        $model->version = 1;

        if(isset($_GET['DownloadFile']))
            $model->attributes=$_GET['DownloadFile'];

        // Uncomment the following line if AJAX validation is needed
        // $this->performAjaxValidation($model);

        if(isset($_POST['DownloadFile']))
        {
            $model->attributes  = $_POST['DownloadFile'];
            $model->mimeType    = $_FILES['DownloadFile']['type']['pathToFile'];
            $uploadedFile       = CUploadedFile::getInstance($model,'pathToFile');
            $model->pathToFile  = $this->module->baseDir;
            $model->fileName    = $uploadedFile->name;

            if($model->save()) {
                if(!empty($uploadedFile))  // check if uploaded file is set or not
                {
                    $uploadedFile->saveAs($model->pathToFile.DIRECTORY_SEPARATOR.md5($model->fileName));  // file will uplode to rootDirectory/files/
                }
                Yii::app()->user->setFlash('success',Yii::t('DownloadModule.main','<strong>Creating New Item</strong><br />The item with ID #{id} has been created.',array('{id}'=>$model->id)));
                $this->redirect(array('view','id'=>$model->id));
            } else {
                Yii::app()->user->setFlash('error',Yii::t('DownloadModule.main','<strong>Error Creating New Item</strong><br />Couldn\'t create a new item.'));
            }
        }

        $this->render('create',array(
            'model'=>$model,
        ));
    } // }}} 
    // {{{ actionUpdate
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate($id)
    {
        $model=$this->loadModel($id);

        // Uncomment the following line if AJAX validation is needed

views/category/_form.php
<div class="form">

<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'id'=>'download-category-form',
    'enableAjaxValidation'=>false,
    'type'=>'horizontal',
    'focus'=>array($model,'parentId'),
)); ?>

    <p class="help-block">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

    <?php echo $form->dropDownListRow($model,'parentId',$model->parentOptions, array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textAreaRow($model,'description',array('class'=>'span5', 'rows'=>3)); ?>

    <?php echo $form->textAreaRow($model,'authItems',array('rows'=>6, 'class'=>'span5')); ?>

    <?php echo $form->radioButtonListRow($model,'status', $model->statusOptions); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>$model->isNewRecord ? Yii::t('DownloadModule.main','Create') : Yii::t('DownloadModule.main','Save'),
            'icon'=>'ok',
        )); ?>
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'reset', 
            'icon'=>'repeat', 
            'label'=>Yii::t('DownloadModule.main','Reset'))); ?>
    </div>

<?php $this->endWidget(); ?>


</div><!-- form -->

views/category/_search.php
<?php $form=$this->beginWidget('bootstrap.widgets.TbActiveForm',array(
    'action'=>Yii::app()->createUrl($this->route),
    'method'=>'get',
)); ?>

    <?php echo $form->textFieldRow($model,'id',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'parentId',array('class'=>'span5')); ?>

    <?php echo $form->textFieldRow($model,'title',array('class'=>'span5','maxlength'=>255)); ?>

    <?php echo $form->textFieldRow($model,'description',array('class'=>'span5')); ?>

    <?php echo $form->textAreaRow($model,'authItems',array('rows'=>6, 'cols'=>50, 'class'=>'span8')); ?>

    <?php echo $form->textFieldRow($model,'status',array('class'=>'span5')); ?>

    <div class="form-actions">
        <?php $this->widget('bootstrap.widgets.TbButton', array(
            'buttonType'=>'submit',
            'type'=>'primary',
            'label'=>Yii::t('DownloadModule.main','Search'),
        )); ?>
    </div>

<?php $this->endWidget(); ?>

views/category/_view.php
<div class="navbar-inner" style="border: 1px solid navy; padding:15px">

    <div class="row-fluid">

    <div class="span3">

	<b><?php echo CHtml::encode($data->getAttributeLabel('title')); ?>:</b><br />
	<?php echo CHtml::link(CHtml::encode($data->title),array('file/index','DownloadFile[categoryId]'=>$data->id)); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('description')); ?>:</b><br />
	<?php echo trim($data->description)=='' ? '&ndash;' : CHtml::encode($data->description); ?>
	<br />

    </div>

    <div class="span3">

	<b><?php echo CHtml::encode($data->getAttributeLabel('parentId')); ?>:</b><br />
	<?php echo $data->getParentLink('files'); ?>
	<br />

	<b><?php echo CHtml::encode($data->getAttributeLabel('status')); ?>:</b><br />
	<?php echo CHtml::encode($data->statusOptions[$data->status]); ?>
	<br />

    <b><?php echo CHtml::encode(Yii::t('DownloadModule.main', 'Files')); ?>:</b><br />
    <?php echo CHtml::link(Yii::t('DownloadModule.main','{n} file|{n} files',array(count($data->files))),array('file/index', 'DownloadFile[categoryId]'=>$data->id)); ?>
    <br />

    </div>

    <div class="span3">

    <b><?php echo CHtml::encode(Yii::t('DownloadModule.main', 'Sub-Categories')); ?>:</b>
    <ul style="list-style-type:none">
        <li><?php echo join("</li>\n\t\t\t<li>", $data->getChildrenLinks('files')); ?></li>
    </ul>
    <br />
    </div>

    </div><!-- end div.row-fluid -->

</div>

views/category/admin.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
    Yii::t('DownloadModule.main','Download Categories')=>array('index'),
    Yii::t('DownloadModule.main','Manage'),
);

$this->menu=array(
    array('label'=>Yii::t('DownloadModule.main','Create New Download Category'),'url'=>array('create'), 'icon'=>'star'),
    array('label'=>Yii::t('DownloadModule.main','List Download Categories'),'url'=>array('index'), 'icon'=>'th-large'),
    array('label'=>Yii::t('DownloadModule.main','Related Links'),'itemOptions'=>array('class'=>'nav-header')),
    array('label'=>Yii::t('DownloadModule.main','Download Files'),'url'=>array('file/admin'), 'icon'=>'th-list'),
);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
    $('.search-form').toggle();
    return false;
});
$('.search-form form').submit(function(){
    $.fn.yiiGridView.update('download-category-grid', {
        data: $(this).serialize()
    });
    return false;
});
");
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','Manage Download Categories')); ?></h1>

<p>
You may optionally enter a comparison operator (<b>&lt;</b>, <b>&lt;=</b>, <b>&gt;</b>, <b>&gt;=</b>, <b>&lt;&gt;</b>
or <b>=</b>) at the beginning of each of your search values to specify how the comparison should be done.
</p>

<?php echo CHtml::link(Yii::t('DownloadModule.main','Advanced Search'),'#',array('class'=>'search-button btn')); ?>
<div class="search-form" style="display:none">
<?php $this->renderPartial('_search',array(
    'model'=>$model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView',array(
    'id'=>'download-category-grid',
    'type'=>'striped condensed',
    'dataProvider'=>$model->search(),
    'filter'=>$model,
    'htmlOptions'=>array('style'=>'cursor: pointer;'),
    'selectionChanged'=>"function(id){window.location='" . Yii::app()->urlManager->createUrl('/download/category/view', array('id'=>'')) . "/' + $.fn.yiiGridView.getSelection(id);}",
    'columns'=>array(
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{view}{update}',
        ),
        array(
            'name'=>'parentId',
            'value'=>'$data->parentlink',
            'type'=>'raw',
        ),
        'title',
        'description',
        'authItems',
        array(
            'name'=>'status',
            'value'=>'$data->statusOptions[$data->status]',
            'filter'=>$model->statusOptions,
        ),
        array(
            'name'=>'filesCount',
            'type'=>'raw',
            'value'=>'CHtml::link(count($data->files),array("file/admin","DownloadFile[categoryId]"=>$data->id))." | "'
                .'.CHtml::link("'.Yii::t('DownloadModule.main','Add File').'",array("file/create","DownloadFile[categoryId]"=>$data->id))',
            'htmlOptions'=>array('style'=>'text-align:center'),
        ),
        array(
            'class'=>'bootstrap.widgets.TbButtonColumn',
            'template'=>'{delete}',
        ),
    ),
)); ?>

views/category/create.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
	Yii::t('DownloadModule.main','Download Categories')=>array('index'),
	Yii::t('DownloadModule.main','Create'),
);

$this->menu=array(
	array('label'=>Yii::t('DownloadModule.main','List Download Categories'),'url'=>array('index'), 'icon'=>'th-large'),
	array('label'=>Yii::t('DownloadModule.main','Manage Download Categories'),'url'=>array('admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','Create a New Download Category')); ?></h1>

<?php echo $this->renderPartial('_form', array('model'=>$model)); ?>

views/category/view.php
<?php
$this->breadcrumbs=array(
    Yii::t('DownloadModule.main','Downloads')=>array('/download'),
	Yii::t('DownloadModule.main','Download Categories')=>array('index'),
	$model->title,
);

$this->menu=array(
	array('label'=>Yii::t('DownloadModule.main','Update Download Category'),'url'=>array('update','id'=>$model->id), 'icon'=>'pencil'),
	array('label'=>Yii::t('DownloadModule.main','User View'),'url'=>array('file/index','DownloadFile[categoryId]'=>$model->id), 'icon'=>'zoom-in'),
	array('label'=>Yii::t('DownloadModule.main','Add New File'),'url'=>array('file/create','DownloadFile[categoryId]'=>$model->id), 'icon'=>'star'),
	array('label'=>Yii::t('DownloadModule.main','Delete Download Category'),'url'=>'#','linkOptions'=>array('submit'=>array('delete','id'=>$model->id),'confirm'=>'Are you sure you want to delete this item?'), 'icon'=>'remove'),
	array('label'=>Yii::t('DownloadModule.main','Create New Download Category'),'url'=>array('create'), 'icon'=>'star'),
	array('label'=>Yii::t('DownloadModule.main','Manage'),'url'=>array('admin'), 'icon'=>'th-list'),
    array('label'=>Yii::t('DownloadModule.main','Related Links'),'itemOptions'=>array('class'=>'nav-header')),
    array('label'=>Yii::t('DownloadModule.main','Download Files'),'url'=>array('file/admin'), 'icon'=>'th-list'),
);
?>

<h1><?php echo CHtml::encode(Yii::t('DownloadModule.main','View Download Category {recordName}',array('{recordName}'=>$model->recordName))); ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView',array(
	'data'=>$model,
	'attributes'=>array(
		array(
            'name'=>'parentId',
            'type'=>'raw',
            'value'=>$model->parentLink,
        ),
		'title',
        array(
            'name'=>'description',
            'type'=>'raw',
            'value'=>nl2br(CHtml::encode($model->description)),
        ),
		'authItems',
        array(
            'name'=>'status',
            'value'=>$model->statusOptions[$model->status],
        ),
        array(
            'label'=>'Sub Categories',
            'type'=>'raw',
            'value'=>'<ul><li>'.join('</li><li>',$model->childrenLinks).'</li></ul>',
        ),
        array(
            'label'=>Yii::t('DownloadModule.main', 'Files'),
            'value'=>CHtml::link(count($model->files),array('file/admin', 'DownloadFile[categoryId]'=>$model->id))
                .'<br />'.CHtml::link('<i class="icon-star icon-white"></i> '.Yii::t('DownloadModule.main','Add New File'),array('file/create', 'DownloadFile[categoryId]'=>$model->id), array('class'=>'btn btn-primary btn-small')),
            'type'=>'raw',
        ),      
	),
)); ?>

<?php $this->widget('ext.diggindata.ddtimestamp.widgets.DDTimestamp', array(
    'model'=>$model, 
    'title'=>Yii::t('site','Change Log'),
    'detailViewWidget'=>'bootstrap.widgets.TbDetailView'
)); ?>